version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build start on `date`
      - echo start node code...
      - npm install
      - export BUCKET=codedeploy-jkn
       - >-
        aws cloudformation package --template-file template.yml --s3-bucket
        $BUCKET --output-template-file outputtemplate.yml
  post_build:
    commands:
      - echo Post build start...
      - pwd
      - ls -la
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
