version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Build start on `date`
      - echo start node code...
      - npm install
  post_build:
    commands:
      - echo Post build start...
      - pwd
      - ls -la
artifacts:
  files:
    - '**/*'
